platform :ios, '10.0'

source 'https://github.com/CocoaPods/Specs.git'

target 'OpenMediationDemo' do
  pod 'AdTimingBidSDK', '5.0.3'
  pod 'Google-Mobile-Ads-SDK', '8.1.0'
  pod 'FBAudienceNetwork', '6.3.0'
  pod 'UnityAds', '3.6.0'
  pod 'VungleSDK-iOS', '6.9.1'
  pod 'AdColony', '4.5.0'
  pod 'AppLovinSDK', '6.15.2'
  pod 'mopub-ios-sdk', '5.14.1'
  pod 'TapjoySDK', '12.8.0'
  pod 'ChartboostSDK', '8.4.0'
  #pod 'Ads-CN', '3.4.2.8'
  pod 'Ads-Global', '3.4.2.8'
  pod 'MintegralAdSDK/RewardVideoAd', '6.7.6'
  pod 'MintegralAdSDK/InterstitialVideoAd', '6.7.6'
  pod 'MintegralAdSDK/BannerAd', '6.7.6'
  pod 'MintegralAdSDK/SplashAd', '6.7.6'
  pod 'MintegralAdSDK/BidRewardVideoAd', '6.7.6'
  pod 'MintegralAdSDK/BidInterstitialVideoAd', '6.7.6'
  pod 'MintegralAdSDK/BidBannerAd', '6.7.6'
  pod 'GDTMobSDK', '4.12.3'
  pod 'IronSourceSDK','7.1.3'
  pod 'ChartboostHelium','2.2.1'
  pod 'Fyber_Marketplace_SDK','7.5.4'
  pod 'SigmobAd-iOS', '2.25.1'
  pod 'KSAdSDK', '3.3.6'
  pod 'HyBid', '2.4.0'
end

